### ISSUE TITLE
Problem importing CYBORG

### ISSUE THREAD

**Issue by Hobstarr** [cage-challenge/cage-challenge-1#9]
Having some trouble importing CybORG. It seems to be installed, and the test runs just fine, but then when I import it either in Pycharm or Jupyter notebook, I get the same problem that is shown below:

<img width="1137" alt="Screenshot 2021-11-18 at 15 56 06" src="https://user-images.githubusercontent.com/56070935/142450631-ec4c45c0-0fc1-43f8-9686-f1a3f38217a2.png">

**Comment by cage-challenge** [comment]
Can you please provide more details on your configuration such as OS version, Python version (3.8 or 3.8.x) and any Python related environment variables plus any other information that might be relevant? It would be good to try running it directly from the command line rather than using a tool to run it and see if the error is still present.

We have seen this error before, but it hasn't been related to a bug as the same code works fine with a different Python version. So maybe you could try running it with a different version of Python.

**Comment by djbow2** [comment]
Is this issue still open?
